name: diagonal_decoration
description: Custom box decoration with diagonals on the background. Contains DiagonalDecoration and MatrixDecoration.
version: 1.0.1+2
repository: https://github.com/yako-dev/flutter-diagonal-decoration
issue_tracker: https://github.com/yako-dev/flutter-diagonal-decoration/issues

topics:
  - ui

screenshots:
  - description: "DiagonalDecoration preview"
    path: images/pub_dev_preview.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
